# Generated by Django 3.1.6 on 2021-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='UNTITLED', max_length=250)),
                ('contributors', models.CharField(max_length=500, null=True)),
                ('iswc', models.CharField(max_length=20, null=True)),
                ('source', models.CharField(default='NO_LABEL', max_length=150)),
                ('id_provider', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Work',
            },
        ),
    ]
