# Generated by Django 3.1.6 on 2021-02-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='source',
        ),
        migrations.RemoveField(
            model_name='work',
            name='contributors',
        ),
        migrations.AddField(
            model_name='work',
            name='sources',
            field=models.ManyToManyField(related_name='labels', to='works.Source'),
        ),
        migrations.AddField(
            model_name='work',
            name='contributors',
            field=models.ManyToManyField(related_name='contributors', to='works.Contributor'),
        ),
    ]
